export const defaultData = {
  name: "Osama Alaaeldin",
  bio: "<p> I am Ryan Adlard, web designer from USA, California. I have rich experience in web site design and building and customization, also I am good at wordpress. I love to talk with you about our unique. </p>",
  age: 24,
  residence: "USA",
  freelance: true,
  address: "California, USA",
  typeingAnimation: ["Web Designer", "Developer", "Freelancer"],
  socialLinks: [
    { id: 1, icons: "fa fa-dribbble", link: "https://dribbble.com/" },
    { id: 2, icons: "fa fa-twitter", link: "https://twitter.com/" },
    { id: 3, icons: "fa fa-github", link: "https://github.com/" },
    { id: 4, icons: "fa fa-spotify", link: "https://www.spotify.com/" },
    {
      id: 4,
      icons: "fa fa-stack-overflow",
      link: "https://stackoverflow.com/",
    },
  ],
  experiences: [
    {
      id: 1,
      jobTitle: "Art Director",
      company: "Facebook Inc.",
      dec: "Collaborate with creative and development teams on the execution of ideas.",
      date: "2013 - Present",
    },
    {
      id: 2,
      jobTitle: "Front-end Developer",
      company: "Google Inc.",
      dec: "Monitored technical aspects of the front-end delivery for several projects.",
      date: "2011 - 2012",
    },
    {
      id: 3,
      jobTitle: "Senior Developer",
      company: "Abc Inc.",
      dec: "Optimize website performance using latest technology.",
      date: "2009 - 2010",
    },
  ],
  educations: [
    {
      id: 1,
      date: "2006 - 2008",
      name: "Art University",
      address: "New York",
      dec: "Bachelor's Degree in Computer Science ABC Technical Institute, Jefferson, Missouri",
    },
    {
      id: 2,
      date: "2005 - 2006",
      name: "Programming Course",
      address: "Paris",
      dec: "Coursework - Git, WordPress, Javascript, iOS, Android.",
    },
    {
      id: 3,
      date: "2004 - 2005",
      name: "Web Design Course",
      address: "London",
      dec: "Converted Photoshop layouts to web pages using HTML, CSS, and JavaScript",
    },
  ],
  services: [
    {
      id: 1,
      icon: "fa fa-html5",
      title: "Front-end",
      desc: "Modern and mobile-ready website that will help you reach all of your marketing.",
    },
    {
      id: 2,
      icon: "fa fa-code",
      title: "Back-End",
      desc: "UI/UX focus on the user, frontend focus on the settings of the user, and backend focus on the data.",
    },
    {
      id: 3,
      icon: "fa fa-wordpress",
      title: "WordPress Development",
      desc: "WordPress development services improve business websites.",
    },
    {
      id: 4,
      icon: "fa fa-server",
      title: "WordPress Security",
      desc: "Security consultants can check the code and scan for vulnerabilities.",
    },
  ],
  pricing: {
    basic: {
      icon: "fa fa-battery-half",
      price: 22,
      details: [
        { id: 1, title: "Web Development", disable: false, new: false },
        { id: 2, title: "Advetising", disable: false, new: false },
        { id: 3, title: "Game Development", disable: false, new: false },
        { id: 4, title: "Music Writing", disable: true, new: false },
        { id: 5, title: "Photography", disable: true, new: true },
      ],
    },
    pro: {
      icon: "fa fa-battery-full",
      price: 48,
      details: [
        { id: 1, title: "Web Development", disable: false, new: false },
        { id: 2, title: "Advetising", disable: false, new: false },
        { id: 3, title: "Game Development", disable: false, new: false },
        { id: 4, title: "Music Writing", disable: false, new: false },
        { id: 5, title: "Photography", disable: false, new: true },
      ],
    },
  },
  funfactItems: {
    title: "Fun Fact",
    items: [
      { id: 1, title: "80 Albumes Listened", icon: "fa fa-music" },
      { id: 2, title: "15 Awards Won", icon: "fa fa-trophy" },
      { id: 3, title: "1 000 Cups of coffee", icon: "fa fa-coffee" },
      { id: 4, title: "10 Countries Visited", icon: "fa fa-flag" },
    ],
  },
  clients: [
    { id: 1, img: "/images/clients/client_1.png" },
    { id: 2, img: "/images/clients/client_2.png" },
    { id: 3, img: "/images/clients/client_3.png" },
    { id: 4, img: "/images/clients/client_4.png" },
  ],
  porgressBar: {
    title: "Design",
    icon: "fa fa-paint-brush",
    skills: [
      { id: 1, name: "Web Design", value: 90 },
      { id: 2, name: "Write Music", value: 65 },
      { id: 3, name: "Photoshop", value: 75 },
      { id: 4, name: "Graphic Design", value: 85 },
    ],
  },
  porgressCircle: {
    title: "Coding",
    icon: "fa fa-code",
    skills: [
      { id: 1, name: "WordPress", value: 90 },
      { id: 2, name: "PHP / MYSQL", value: 65 },
      { id: 3, name: "Angular / JavaScript", value: 75 },
      { id: 4, name: "HTML / CSS", value: 85 },
    ],
  },
  knowledge: {
    title: "Knowledge",
    icons: "fa fa-list",
    items: [
      { id: 1, text: "Website hosting" },
      { id: 2, text: "iOS and android apps" },
      { id: 3, text: "Create logo design" },
      { id: 4, text: "Design for print" },
      { id: 5, text: "Modern and mobile-ready" },
      { id: 6, text: "Advertising services include" },
      { id: 7, text: "Graphics and animations" },
      { id: 8, text: "Search engine marketing" },
    ],
  },
};
export const musician = {
  name: "Paul Johnson",
  bio: "<p> <strong>Hello! I’m Paul Johnson.</strong> and I have been bringing old-time, good-time jug band music to audiences in western New York since 2008. Hailed as “America’s happiest music” jug band music has its roots in the country blues. </p>",
  age: 27,
  residence: "USA",
  freelance: true,
  address: "New York, USA",
  typeingAnimation: ["Musician", "Composer", "Singer", "Instrumentalist"],
  socialLinks: [
    { id: 1, icons: "fa fa-soundcloud", link: "https://soundcloud.com/" },
    { id: 2, icons: "fa fa-bandcamp", link: "https://bandcamp.com/" },
    { id: 3, icons: "fa fa-mixcloud", link: "https://mixcloud.com/" },
    { id: 4, icons: "fa fa-twitter", link: "https://twitter.com/" },
    {
      id: 4,
      icons: "fa fa-instagram",
      link: "https://instagram.com/",
    },
  ],
  experiences: [
    {
      id: 1,
      jobTitle: "Schenectady Symphony Orchestra",
      company: "New York",
      dec: "Third chair, first violin section.",
      date: "2023 - Present",
    },
    {
      id: 2,
      jobTitle: "Utica Symphony Orchestra",
      company: "New York",
      dec: "First violin section; orchestra is currently without contract.",
      date: "2023 - 2023",
    },
    {
      id: 3,
      jobTitle: "Frequent freelance",
      company: "New York",
      dec: "Work in: New York Capital Region for Cohoes Music Hall, Hubbard Hall Opera Theater.",
      date: "2014 - 2023",
    },
  ],
  educations: [
    {
      id: 1,
      date: "2011 - 2014",
      name: "Peabody Institute",
      address: "Baltimore",
      dec: "M.M. in Performance, Peabody Institute – Baltimore, MD 2015.",
    },
    {
      id: 2,
      date: "2008 - 2011",
      name: "American University",
      address: "Washington",
      dec: "B.A. in Music, American University – Washington, D.C. 2012.",
    },
    {
      id: 3,
      date: "2000 - 2008",
      name: "New York School of Music",
      address: "New York",
      dec: "Great school! The teachers really care about the students.",
    },
  ],
  services: [
    {
      id: 1,
      icon: "fa fa-microphone",
      title: "Lead Vocal",
      desc: "The lead vocalist in popular music is typically the member of a group.",
    },
    {
      id: 2,
      icon: "fa fa-music",
      title: "Record Guitars",
      desc: "Music copying, writing, creating, transcription, arranging and composition services.",
    },
    {
      id: 3,
      icon: "fa fa-soundcloud",
      title: "Soundcloud Mix",
      desc: "Made a great new DJ mix and you want to get it online and out to the world",
    },
    {
      id: 4,
      icon: "fa fa-gamepad",
      title: "Music for Games, Apps",
      desc: "Developing tracks and unique music for android, ios and video games.",
    },
  ],
  pricing: {
    basic: {
      icon: "fa fa-volume-down",
      price: 22,
      details: [
        { id: 1, title: "Lead Vocal", disable: false, new: false },
        { id: 2, title: "Record Guitars", disable: false, new: false },
        { id: 3, title: "Soundcloud Mix", disable: false, new: false },
        { id: 4, title: "Music for Games", disable: true, new: true },
        { id: 5, title: "Music for Apps", disable: true, new: true },
      ],
    },
    pro: {
      icon: "fa fa-volume-up",
      price: 48,
      details: [
        { id: 1, title: "Lead Vocal", disable: false, new: false },
        { id: 2, title: "Record Guitars", disable: false, new: false },
        { id: 3, title: "Soundcloud Mix", disable: false, new: false },
        { id: 4, title: "Music for Games", disable: false, new: true },
        { id: 5, title: "Music for Apps", disable: false, new: true },
      ],
    },
  },
  clients: [
    { id: 1, img: "/images/clients/client_1.png" },
    { id: 2, img: "/images/clients/client_2.png" },
    { id: 3, img: "/images/clients/client_3.png" },
    { id: 4, img: "/images/clients/client_4.png" },
  ],
  porgressBar: {
    title: "Design",
    icon: "fa fa-paint-brush",
    skills: [
      { id: 1, name: "Motivation / Determination", value: 90 },
      { id: 2, name: "Violin Expertise", value: 65 },
      { id: 3, name: "Creativity", value: 75 },
      { id: 4, name: "Guitar Expertise", value: 85 },
    ],
  },
  porgressCircle: {
    title: "Read Music",
    icon: "fa fa-music",
    skills: [
      { id: 1, name: "Chords", value: 90 },
      { id: 2, name: "Intervals", value: 75 },
      { id: 3, name: "Melody", value: 85 },
      { id: 4, name: "Pitch", value: 95 },
    ],
  },
  knowledge: {
    title: "Knowledge",
    icons: "fa fa-list",
    items: [
      { id: 1, text: "A Tight Sense of Rhythm" },
      { id: 2, text: "Rhythm is the heartbeat of all music" },
      { id: 3, text: "An Accurate Sense of Pitch" },
      { id: 4, text: "The Ability to “Jam”" },
      { id: 5, text: "An Ability to “Talk Music”" },
      { id: 6, text: "Singing in Tune" },
    ],
  },
};
export const writer = {
  name: "Paul Johnson",
  bio: "<p> I'm <strong>Demetrius Bernard</strong> author bestseller books, won the Hugo Award for Best Novel. Writing science fiction, including the New York Times bestseller. I also writes non-fiction, on subjects ranging from personal finance to astronomy to film. </p>",
  age: 24,
  residence: "USA",
  freelance: true,
  address: "New York, USA",
  typeingAnimation: ["Writer", "Author", "Blogger"],
  socialLinks: [
    { id: 1, icons: "fa fa-medium", link: "https://medium.com/" },
    { id: 2, icons: "fa fa-twitter", link: "https://twitter.com/" },
    { id: 3, icons: "fa fa-facebook-f", link: "https://facebook.com/" },
    { id: 4, icons: "fa fa-linkedin", link: "https://linkedin.com/" },
  ],
  experiences: [
    {
      id: 1,
      jobTitle: "Writer Director",
      company: "DBBooks",
      dec: "Collaborate with creative and development teams on the execution of ideas.",
      date: "2013 - Present",
    },
    {
      id: 2,
      jobTitle: "Team Leader",
      company: "ABC Inc.      ",
      dec: "A team leader is responsible for guiding a group of employees as they complete a project.",
      date: "2011 - 2012",
    },
    {
      id: 3,
      jobTitle: "Business Writer",
      company: "Writer Corporation.",
      dec: "Corporate writing is writing for business purposes.",
      date: "2009 - 2010",
    },
  ],
  educations: [
    {
      id: 1,
      date: "2006 - 2008",
      name: "New York University",
      address: "New York",
      dec: "New York University offers 2 Creative Writing Degree programs. It's a large private university in a large city.",
    },
    {
      id: 2,
      date: "2005 - 2006",
      name: "Writing Course",
      address: "London",
      dec: "Creative writing short courses is taught at City, University of London. Develop writing skills with professional and published authors.",
    },
    {
      id: 3,
      date: "2004 - 2005",
      name: "New York School",
      address: "Brooklyn, NY, United States",
      dec: "",
    },
  ],
  services: [
    {
      id: 1,
      icon: "fa fa-book",
      title: "Writing Books",
      desc: "Write the argument of your book in a sentence, then stretch that out to a paragraph.",
    },
    {
      id: 2,
      icon: "fa fa-video-camera",
      title: "Screenwriting",
      desc: "Spec scripts are feature film or television show scripts written on speculation of sale.",
    },
    {
      id: 3,
      icon: "fa fa-newspaper-o",
      title: "Writing Newspaper",
      desc: "news-writing style is the prose style used for news reporting in media such as television.",
    },
    {
      id: 4,
      icon: "fa fa-gamepad",
      title: "Writing Resumes",
      desc: "professional resume-writing service has helped over 400,000 professionals land more interviews.",
    },
  ],
  pricing: {
    basic: {
      icon: "fa fa-file-o",
      price: 22,
      details: [
        { id: 1, title: "Writing Books", disable: false, new: false },
        { id: 2, title: "Screenwriting", disable: false, new: false },
        { id: 3, title: "Writing Newspaper", disable: false, new: false },
        { id: 4, title: "Writing Resumes", disable: true, new: true },
      ],
    },
    pro: {
      icon: "fa fa-files-o",
      price: 48,
      details: [
        { id: 1, title: "Writing Books", disable: false, new: false },
        { id: 2, title: "Screenwriting", disable: false, new: false },
        { id: 3, title: "Writing Newspaper", disable: false, new: false },
        { id: 4, title: "Writing Resumes", disable: false, new: true },
      ],
    },
  },
  funfactItems: {
    title: "Awards",
    items: [
      { id: 1, title: "New York Book Awards", icon: "fa fa-book" },
      { id: 2, title: "German Book Awards", icon: "fa fa-trophy" },
      { id: 3, title: "Costa Book Award", icon: "fa fa-coffee" },
      { id: 4, title: "Writers Guild Awards", icon: "fa fa-pencil" },
    ],
  },
  porgressBar: {
    title: "Design",
    icon: "fa fa-paint-brush",
    skills: [
      { id: 1, name: "The Ability to Communicate", value: 90 },
      { id: 2, name: "The Power of Observation", value: 65 },
      { id: 3, name: "Reasoning and Problem Solving", value: 75 },
      { id: 4, name: "Knowledge of Grammar, Spelling", value: 85 },
    ],
  },
  knowledge: {
    title: "Knowledge",
    icons: "fa fa-list",
    items: [
      { id: 1, text: "Adaptability" },
      { id: 2, text: "Strong Research Skills" },
      { id: 3, text: "The Ability to Get Focused" },
      { id: 4, text: "Communicate" },
      { id: 5, text: "The Ability to Meet Deadlines" },
      { id: 6, text: "Organizational Skills" },
    ],
  },
};
export const lawyer = {
  name: "Casandra Wood",
  bio: "<p> <strong>Hello! I’m Casandra Wood.</strong><br> Lawyer from UK, London. I have licensed by the state in which I practice to advise and represent clients on legal matters including animal rights. </p>",
  age: 26,
  residence: "UK",
  freelance: true,
  address: "London, UK",
  socialLinks: [
    { id: 1, icons: "fa fa-facebook-f", link: "https://facebook.com/" },
    { id: 2, icons: "fa fa-twitter", link: "https://twitter.com/" },
    { id: 3, icons: "fa fa-instagram", link: "https://instagram.com/" },
    { id: 4, icons: "fa fa-spotify", link: "https://spotify.com/" },
  ],
  experiences: [
    {
      id: 1,
      jobTitle: "Law Director",
      company: "Facebook Inc.",
      dec: "Head of the Law Department which represents and advises the City in all civil.",
      date: "2013 - Present",
    },
    {
      id: 2,
      jobTitle: "Lawyer Leader",
      company: "Google Inc.",
      dec: "Was part of a client focused organisation that makes a difference.",
      date: "2011 - 2012",
    },
    {
      id: 3,
      jobTitle: "Junior Lawyer",
      company: "ABC Inc.",
      dec: "A fast-growing international pharmaceutical services company.",
      date: "2009 - 2010",
    },
  ],
  educations: [
    {
      id: 1,
      date: "2006 - 2008",
      name: "Law University",
      address: "London",
      dec: "Gray's Inn, 4 Gray's Inn Place, Warwick Ct",
    },
    {
      id: 2,
      date: "2005 - 2006",
      name: "Law Schools",
      address: "London",
      dec: "The Law School of English has over 50 years experience teaching general.",
    },
    {
      id: 3,
      date: "2004 - 2005",
      name: "London School",
      address: "London",
      dec: "The London School of English has over 100 years experience teaching general.",
    },
  ],
  services: [
    {
      id: 1,
      icon: "fa fa-balance-scale",
      title: "Criminal Law",
      desc: "Proscribes conduct perceived as threatening, harmful, or otherwise endangering to the property.",
    },
    {
      id: 2,
      icon: "fa fa-bank",
      title: "Business Law",
      desc: "governs business and commerce and is often considered to be a branch of civil law and deals",
    },
    {
      id: 3,
      icon: "fa fa-gavel",
      title: "Legal Services",
      desc: "Provides a wide range of legal services in all regions of London.",
    },
    {
      id: 4,
      icon: "fa fa-money",
      title: "Finance",
      desc: "Provides a wide range of finance services in all regions of London.",
    },
  ],
  pricing: {
    basic: {
      icon: "fa fa-user",
      price: 22,
      details: [
        { id: 1, title: "Criminal Law", disable: false, new: false },
        { id: 2, title: "Business Law", disable: false, new: false },
        { id: 3, title: "Legal Services", disable: true, new: true },
        { id: 4, title: "Finance Services", disable: true, new: true },
      ],
    },
    pro: {
      icon: "fa fa-users",
      price: 48,
      details: [
        { id: 1, title: "Criminal Law", disable: false, new: false },
        { id: 2, title: "Business Law", disable: false, new: false },
        { id: 3, title: "Legal Services", disable: false, new: true },
        { id: 4, title: "Finance Services", disable: false, new: true },
      ],
    },
  },
  porgressBar: {
    title: "Design",
    icon: "fa fa-paint-brush",
    skills: [
      { id: 1, name: "Oral Communication", value: 90 },
      { id: 2, name: "Written Communication", value: 65 },
      { id: 3, name: "Analytical and Logical Reasoning", value: 75 },
      { id: 4, name: "Legal Research", value: 85 },
    ],
  },
  knowledge: {
    title: "Knowledge",
    icons: "fa fa-list",
    items: [
      { id: 1, text: "Client Service" },
      { id: 2, text: "Technology Skills" },
      { id: 3, text: "Knowledge of Substantive Law" },
      { id: 4, text: "Legal Procedure" },
      { id: 5, text: "Organization" },
      { id: 6, text: "Teamwork" },
    ],
  },
};

export const fitnessTrainer = {
  name: "Daniel Wilson",
  bio: "<p> <strong>Hello!</strong> Personal &amp; Fitness trainer from USA, New York. I have knowledge of general fitness involved in exercise prescription and motivate clients by setting goals, providing feedback. </p>",
  age: 30,
  residence: "USA",
  freelance: true,
  address: "New York, USA",
  typeingAnimation: ["Personal Trainer", "Body builder", "Fitness Trainer"],
  socialLinks: [
    { id: 3, icons: "fa fa-instagram", link: "https://instagram.com/" },
    { id: 2, icons: "fa fa-twitter", link: "https://twitter.com/" },
    { id: 1, icons: "fa fa-facebook-f", link: "https://facebook.com/" },
    { id: 4, icons: "fa fa-spotify", link: "https://spotify.com/" },
  ],
  experiences: [
    {
      id: 1,
      jobTitle: "Fitness Trainer",
      company: "Gym Club",
      dec: "Inspired clients to push their hardest and do their very best.",
      date: "2013 - Present",
    },
    {
      id: 2,
      jobTitle: "Cardio Trainer",
      company: "High-Intensity Complex",
      dec: "Dynamic sculpting exercises for the perfect balance of cardio and strength training.",
      date: "2011 - 2012",
    },
  ],
  educations: [
    {
      id: 1,
      date: "2006 - 2008",
      name: "Pace University",
      address: "New York",
      dec: "Pace University is a private university with its main campus in New York City.",
    },
    {
      id: 2,
      date: "2005 - 2006",
      name: "Fitness Course",
      address: "London",
      dec: "Personal trainer and fitness instructor courses in London.",
    },
  ],
  services: [
    {
      id: 1,
      icon: "fa fa-child",
      title: "Fitness Trainer",
      desc: "We offer personal training and nutrition coaching to help you achieve goals faster!",
    },
    {
      id: 2,
      icon: "fa fa-heartbeat",
      title: "Cardio Training",
      desc: "Cardio training increases endurance, and hence the intensity of training.",
    },
    {
      id: 3,
      icon: "fa fa-circle",
      title: "Workout Training",
      desc: "Medicine balls are versatile, portable and a fad that’s lasted the test of time.",
    },
    {
      id: 4,
      icon: "fa fa-cutlery",
      title: "Proper Nutrition",
      desc: "Good nutrition is an important part of leading a healthy lifestyle.",
    },
  ],
  pricing: {
    basic: {
      icon: "fa fa-battery-half",
      price: 22,
      details: [
        { id: 1, title: "Fitness Training", disable: false, new: false },
        { id: 2, title: "Cardio Training", disable: false, new: false },
        { id: 3, title: "Workout Training", disable: true, new: false },
        { id: 4, title: "Proper Nutrition", disable: true, new: false },
      ],
    },
    pro: {
      icon: "fa fa-battery-full",
      price: 48,
      details: [
        { id: 1, title: "Fitness Training", disable: false, new: false },
        { id: 2, title: "Cardio Training", disable: false, new: false },
        { id: 3, title: "Workout Training", disable: false, new: false },
        { id: 4, title: "Proper Nutrition", disable: false, new: false },
      ],
    },
  },
  porgressBar: {
    title: "Fitness",
    icon: "fa fa-bicycle",
    skills: [
      { id: 1, name: "Agility", value: 90 },
      { id: 2, name: "Balance", value: 65 },
      { id: 3, name: "Power", value: 75 },
      { id: 4, name: "Speed", value: 85 },
    ],
  },
  knowledge: {
    title: "Knowledge",
    icons: "fa fa-list",
    items: [
      { id: 1, text: "Fat Burn" },
      { id: 2, text: "Body condition" },
      { id: 3, text: "Strength training" },
      { id: 4, text: "Faster exercise" },
      { id: 5, text: "Bodybuilding" },
      { id: 6, text: "Fitness training" },
      { id: 7, text: "Cardio training" },
    ],
  },
};

export const designer = {
  name: "Jason Allen",
  bio: "<p> <strong>Hello! I’m Jason Allen.</strong> Designer &amp; Photographer from USA, California. I have rich experience in web site design and photography. I love to talk with you about our unique. </p>",
  age: 24,
  residence: "USA",
  freelance: true,
  address: "California, USA",
  typeingAnimation: ["Designer", "Photographer", "Artist"],

  services: [
    {
      id: 1,
      title: "Logo Design",
      icon: "fa fa-pencil",
      desc: "Our logo design starts at a low price with options to meet any budget.",
    },
    {
      id: 2,
      title: "Business Design",
      icon: "fa fa-vcard-o",
      desc: "With freelance business card designers across the globe competing on your project",
    },
    {
      id: 3,
      title: "Photography",
      icon: "fa fa-camera",
      desc: "Full-day or half-day photo shoots with all necessary equipment.",
    },
    {
      id: 4,
      title: "Web Design",
      icon: "fa fa-television",
      desc: "On average Webs theme projects start to receive designs within a few hours.",
    },
  ],
  pricing: {
    basic: {
      icon: "fa fa-battery-half",
      price: 22,
      details: [
        { id: 1, title: "Web Design", disable: false, new: false },
        { id: 2, title: "Mobile-First", disable: false, new: false },
        { id: 3, title: "Graphic Design", disable: true, new: false },
        { id: 4, title: "Logo Design", disable: true, new: false },
        { id: 5, title: "Photography", disable: true, new: false },
      ],
    },
    pro: {
      icon: "fa fa-battery-full",
      price: 48,
      details: [
        { id: 1, title: "Web Design", disable: false, new: false },
        { id: 2, title: "Mobile-First", disable: false, new: false },
        { id: 3, title: "Graphic Design", disable: false, new: false },
        { id: 4, title: "Logo Design", disable: false, new: true },
        { id: 5, title: "Photography", disable: false, new: true },
      ],
    },
  },
  porgressBar: {
    title: "Software Skills",
    icon: "fa fa-paint-brush",
    skills: [
      { id: 1, name: "Sketch", value: 90 },
      { id: 2, name: "Adobe Photoshop", value: 65 },
      { id: 3, name: "Adobe illustration", value: 75 },
      { id: 4, name: "Figma", value: 85 },
    ],
  },
  porgressCircle: {
    title: "Design",
    icon: "fa fa-paint-brush",
    skills: [
      { id: 1, name: "Logo Design", value: 90 },
      { id: 2, name: "Web Design", value: 65 },
      { id: 3, name: "Illustration", value: 75 },
      { id: 4, name: "Photography", value: 85 },
    ],
  },
};

export const programmer = {
  name: "Osama Alaaeldin",
  bio: "<p> <strong>Hello! I’m Donald Wellborn.</strong> Back-end &amp; Frond-end developer from UK, London. I have rich experience in wordpress, also I am good at Magento. I love to talk with you about our unique. </p>",
  age: 30,
  residence: "UK",
  freelance: true,
  address: "London, UK",
  typeingAnimation: [
    "Back-end Developer",
    "Front-end Developer",
    "Freelancer",
    "Programmer",
  ],
  pricing: {
    basic: {
      icon: "fa fa-battery-half",
      price: 22,
      details: [
        { id: 1, title: "WorPress Development", disable: false, new: false },
        { id: 2, title: "Installation Services", disable: false, new: false },
        { id: 3, title: "SEO Audit", disable: false, new: false },
        { id: 4, title: "Hosting & Domain", disable: true, new: false },
        { id: 5, title: "WordPress Security", disable: true, new: false },
      ],
    },
    pro: {
      icon: "fa fa-battery-full",
      price: 48,
      details: [
        { id: 1, title: "WorPress Development", disable: false, new: false },
        { id: 2, title: "Installation Services", disable: false, new: false },
        { id: 3, title: "SEO Audit", disable: false, new: false },
        { id: 4, title: "Hosting & Domain", disable: false, new: true },
        { id: 5, title: "WordPress Security", disable: false, new: true },
      ],
    },
  },
  porgressBar: {
    title: "Front-end",
    icon: "fa fa-paint-brush",
    skills: [
      { id: 1, name: "Java", value: 90 },
      { id: 2, name: "Angular", value: 65 },
      { id: 3, name: "jQuery", value: 75 },
      { id: 4, name: "HTML", value: 85 },
    ],
  },
};

export const blogs = [
  {
    id: 1,
    img: "/images/blog/blog1.jpg",
    date: "APRIL 28, 2020",
    title: "By spite about do of allow",
    category: "Design",
  },
  {
    id: 2,
    img: "/images/blog/blog2.jpg",
    date: "APRIL 28, 2020",
    title: "By spite about do of allow",
    category: "Coding",
  },
  {
    id: 3,
    img: "/images/blog/blog3.jpg",
    date: "APRIL 28, 2020",
    title: "By spite about do of allow",
    category: "Travel",
  },
  {
    id: 4,
    img: "/images/blog/blog1.jpg",
    date: "APRIL 28, 2020",
    title: "By spite about do of allow",
    category: "Coding",
  },
];
